export const mockData = {
    data: {
        users: [
            {
                id: '',
                name: '',
                cart: {
                    id: '',
                    cartItems: [
                        {
                            id: '1',
                            name: '<UNK>',
                        },
                    ],
                },
            },
            {},
        ],
        productTypes: [
            {
                id: '1',
                name: 'dresses',
                productOrderIds: [1, 2],
                products: [
                    {
                        _id: '68f1f8010b5dc27f73097aac',
                        name: 'Rustic Elegance Casual Dress',
                        description:
                            'Introducing the Rustic Elegance Casual Dress from our ModCloth namesake label, a piece that encapsulates the essence of autumn with its warm, navy plaid pattern. Made from the softest Huiyuan cotton, this woven beauty brings both comfort and sartorial elegance to your everyday wardrobe. The dress features functional buttons down the front, allowing you to adjust the fit and style to your liking. Whether you’re heading to the office, a weekend brunch, or a crisp fall picnic, this dress is versatile enough to suit any occasion. Its timeless design and durable fabric ensure it will be a staple in your closet through this season and many more to come.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41.5,
                        origin: 'Imported',
                        material: '100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'rustic-elegance-casual-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760688129639,
                        updatedAt: null,
                        _destroy: false,
                        images: [
                            {
                                _id: '',
                                productId: '',
                                productType: '',
                            },
                            {},
                        ],
                    },
                    {
                        _id: '68f1f9d00b5dc27f73097ab2',
                        name: 'Twilight Serenade Midi Dress',
                        description:
                            'From our ModCloth namesake label comes the Twilight Serenade Midi Dress, a nostalgic ode to vintage charm with a modern twist. Clad in a rich purple check, this knit piece offers a flattering double scoop neck top and a contrasting skirt, accented with a sash waist for a defined silhouette. Medium stretch ensures comfort and flexibility, while a discreet pocket adds a functional touch. Ideal for festive gatherings or cozy winter dates, this dress guarantees a stunning entrance.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 49,
                        origin: 'Imported',
                        material: '92% Polyester, 8%, Elastane',
                        productTypeName: 'dresses',
                        slug: 'twilight-serenade-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760688592878,
                        updatedAt: null,
                        _destroy: false,
                        images: [
                            {
                                _id: '',
                                productId: '',
                                productType: '',
                            },
                            {},
                        ],
                    },
                    {
                        _id: '68f1fb620b5dc27f73097abd',
                        name: 'Instant Energy Faux-Wrap Long Sleeve Knit Dress',
                        description:
                            'When your wardrobe calls for an instant boost, this faux-wrap knit dress from our ModCloth namesake label delivers. Crafted in classic black, this soft, stretchy piece balances cozy comfort with twirl-worthy elegance. A flattering faux-wrap bodice, long sleeves, and a self-tie waist create timeless shape, while hidden side pockets keep your essentials close. Whether styled with bold tights, polished boots, or your favorite statement earrings, this dress makes effortless chic your default setting.',
                        price: 79,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 40,
                        origin: 'Imported',
                        material: '100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'instant-energy-faux-wrap-long-sleeve-knit-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760688994321,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f1fc250b5dc27f73097ac3',
                        name: 'The Enchanted Study Fit & Flare Dress',
                        description:
                            'Step into a world of wonder with the Enchanted Study Dress from our ModCloth namesake label. In our Herbology print, scattered with mushrooms, ferns, berries, and blooms, this vintage-inspired mini is brimming with forest charm. A crisp contrast collar and silky bow tie add scholarly sweetness, while puff sleeves, pockets, and a pleated mini skirt keep it playful and practical. Whether you’re tending to plants, studying spells, or just strolling through autumn leaves, this dress brings a little magic to your everyday.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 35,
                        origin: 'Imported',
                        material: 'Shell and Contrast: 100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'the-enchanted-study-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760689189131,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f1fd480b5dc27f73097ac9',
                        name: 'Ivy League Charm Fit & Flare Dress',
                        description:
                            'Smart style meets vintage flair in the Ivy League Charm Fit & Flare Dress from our ModCloth namesake label. Designed in Cranberry Scholar Plaid, this beauty features a refined shawl collar, empire waist, and a row of classic buttons for timeless appeal. The hi-low hemline adds a modern edge, while puff sleeves and handy pockets keep it effortlessly wearable. Whether you’re headed to class, a cozy café, or a crisp autumn stroll, this dress is top of the style honor roll.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 40,
                        origin: 'Imported',
                        material: '67% Polyester, 30% Viscose, 3% Elastane',
                        productTypeName: 'dresses',
                        slug: 'ivy-league-charm-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760689480620,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f1fe450b5dc27f73097acf',
                        name: 'Cute as a Nutmeg Fit & Flare Dress',
                        description:
                            'Meet your new autumn favorite from our ModCloth namesake label—the Cute as a Nutmeg Fit & Flare Dress in Cranberry Plaid. This sleeveless beauty features a rich blend of burgundy, tan, and forest green woven into a classic plaid pattern, giving it a timeless academic charm with a seasonal twist. Its flattering fit & flare silhouette makes it as perfect for layering over a collared blouse as it is for wearing solo with tights and boots. Whether you’re headed to class, the library, or a cozy coffee date, this dress adds a polished yet playful touch to every outing.',
                        price: 79,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 35,
                        origin: 'Imported',
                        material: '77% Polyester, 20% Viscose, 3% Elastane',
                        productTypeName: 'dresses',
                        slug: 'cute-as-a-nutmeg-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760689733035,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f1ff780b5dc27f73097ad6',
                        name: 'Haute Headmistress Dress',
                        description:
                            'Command the room in the Haute Headmistress Dress from our ModCloth namesake label. Crafted in a moody black-and-grey Midnight Grid plaid, its structured square neckline, puffed 3/4 length sleeves, and tailored fit brings a sharp sophistication to your wardrobe. The dramatic shoulders balance its sleek, modern cut, while subtle front pocket detailing adds a touch of vintage charm. Whether you’re channeling dark academia energy or simply dressing to impress, this mini makes the perfect uniform for evenings spent plotting brilliance over candlelight.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 34,
                        origin: 'Imported',
                        material: '69% Polyester, 26% Viscose, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'haute-headmistress-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760690040170,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f200980b5dc27f73097adc',
                        name: 'Romantic Memories Fit And Flare Dress',
                        description:
                            'Sweep into every soirée with timeless charm in this fit and flare dress from our ModCloth namesake label. This dreamy black beauty features a sheer overlay scattered with velvet polka dots, creating a play of texture that feels both whimsical and elegant. The flattering V-neckline, wide waistband, and voluminous skirt give vintage glamour its modern moment, while a satin sash ties it all together with a bow. Perfect for candlelit dinners, fancy fêtes, or any night you want to feel like the main character.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 44,
                        origin: 'Imported',
                        material: 'Lining: 97% Polyester, 3% Elastane',
                        productTypeName: 'dresses',
                        slug: 'romantic-memories-fit-and-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760690328147,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f201480b5dc27f73097ae2',
                        name: 'Midsummer Flutter Fit & Flare Dress',
                        description:
                            'Capture the essence of vintage charm with the Midsummer Flutter Fit & Flare Dress from our ModCloth namesake label. This woven dress, adorned with a smock panel and zipper closure, offers a figure-flattering silhouette. Ideal for holiday parties or romantic dinners, its ruffled shoulder straps add a whimsical touch. Layer with a faux fur coat for a stunning winter look.',
                        price: 99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 42.75,
                        origin: 'Imported',
                        material: 'Shell and Contrast: 100% Polyamide',
                        productTypeName: 'dresses',
                        slug: 'midsummer-flutter-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760690504932,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f202000b5dc27f73097ae8',
                        name: 'Raven About You Fit & Flare Dress',
                        description:
                            'Channel retro glam with a twist of mystery in our Marilyn-neck fit and flare dress, shown here in the Blackbird print. Against a rich green backdrop, inky blackbirds wind through blooming pink roses, skulls, and coiling snakes for a look that’s equal parts dark romance and vintage charm. The ruched bust with pearl buttons, smocked back, and flattering fit-and-flare silhouette keep comfort and style in perfect harmony—making this dress a showstopper for any occasion that calls for a little enchantment.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 34,
                        origin: 'Imported',
                        material: '100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'raven-about-you-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760690688396,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f203410b5dc27f73097aee',
                        name: 'Bon Chic, Bon Collared Dress',
                        description:
                            'Ooh la la! Say bonjour to charm with the Bon Chic, Bon Collared Dress from our ModCloth namesake label, in the playful Baguette About It print. With its sweet scalloped collar, gathered waist, and breezy long sleeves, this cotton beauty feels like a storybook stroll through the streets of Paris. Whether you’re twirling under the Eiffel Tower or simply sipping a latte at your favorite café, this dress keeps things chic, cheeky, and très magnifique.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37,
                        origin: 'Imported',
                        material: 'Shell: 100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'bon-chic-bon-collared-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760691009772,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f205380b5dc27f73097af4',
                        name: 'Rustic Elegance Casual Dress',
                        description:
                            'Serve up a look that’s equal parts charming and cheeky with this fit-and-flare dress from our ModCloth namesake label. Crafted from breathable cotton and sprinkled all over with our Purrfectly Baked print—featuring loaves, slices, and kitty-faced buns—it’s the recipe for irresistible everyday style. The button-front design and tie waist keep it classic, while hidden side pockets are ready for snacks (or secrets). Whether you’re headed to brunch, the bookshop, or just out to loaf around, this dress rises to every occasion.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: 'Shell: 100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'rustic-elegance-casual-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760691512050,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f2064b0b5dc27f73097afa',
                        name: 'The Carousel Cutie Dress',
                        description:
                            'Step right up and spin into charm with the Carousel Cutie Dress from our ModCloth namesake label! Crafted in a crisp raspberry plaid cotton, this sleeveless beauty cinches at the waist with a self-tie sash and cascades into a twirl-ready skirt. Darling details like a button-up front and collared neckline give it a timeless, vintage-inspired finish. Whether you’re strolling through the fairgrounds, picnicking in the park, or simply turning hallways into runways, this dress makes every moment a main attraction.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: 'Shell: 100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'the-carousel-cutie-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760691787829,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f206ca0b5dc27f73097b00',
                        name: 'Houndstooth and Nail Dress',
                        description:
                            'Nail your look in the Houndstooth and Nail Dress from our ModCloth namesake label. This fit-and-flare stunner features a timeless black-and-white houndstooth print, accented by a keyhole neckline and crisp white contrast collar with button detail. Ruffled cuffs add a playful twist, while hidden side pockets bring everyday practicality. Pair it with tights and loafers for an office-ready ensemble, or heels and red lipstick for instant retro drama.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37,
                        origin: 'Imported',
                        material: '99% Polyester, 1% Elastane',
                        productTypeName: 'dresses',
                        slug: 'houndstooth-and-nail-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760691914826,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f207d30b5dc27f73097b06',
                        name: 'Ghouls Just Wanna Have Fun Dress',
                        description:
                            'Step into spooky-chic style with the Ghouls Just Wanna Have Fun Dress from our ModCloth namesake label. This short-sleeve fit-and-flare features a scoop neckline with a rounded collar, a button-front placket, and an elastic waist for all-day comfort. Complete with pockets, it’s finished in the Sweet Shiver print — a quirky mix of owls, black cats, skeletons, candy, and pumpkins — making it a frightfully fun pick for Halloween and beyond.',
                        price: 59,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 36,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'ghouls-just-wanna-have-fun-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760692179672,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f208640b5dc27f73097b0c',
                        name: 'A Flair for Knowledge Dress',
                        description:
                            'Show off your smarts and your style in the Flair for Knowledge Dress from our ModCloth namesake label. This fit-and-flare silhouette features a figure flattering contrast bodice, a gathered skirt with handy pockets, and a self-tie sash at the waist. Finished in the Stacked Stories print of colorful books, it’s a clever mix of academic charm and vintage-inspired flair—perfect for class, coffee dates, or your next chapter in style.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 38,
                        origin: 'Imported',
                        material: '100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'a-flair-for-knowledge-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760692324657,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f209520b5dc27f73097b12',
                        name: 'Sum Thing Special Fit & Flare Dress',
                        description:
                            'Look sharp in the Sum Thing Special Dress from our ModCloth namesake label. This sleeveless silhouette features contrast trim at the collar and hem, a fitted waist, and a flared skirt with handy pockets. Covered in the Trigonometry Time print of playful equations and geometric doodles, it’s a clever twist on classroom chic that’s perfect layered with cardigans or worn solo for standout smart style.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37,
                        origin: 'Imported',
                        material: '100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'sum-thing-special-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760692562314,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f20a530b5dc27f73097b18',
                        name: 'Going Out And About Dress',
                        description:
                            'Introducing our vintage-inspired shirt dress from the ModCloth namesake label. This dress combines timeless charm with all-day comfort, boasting an elevated silhouette that exudes elegance. Crafted from a lightweight woven fabric, it effortlessly drapes over the body, channeling the charm of the 1940s and 1950s. The dress features a rounded notch collar, delicate corded piping, a full button-up front, a removable sash tie-belt, and front slant pockets at the hips. With its stylish easy-fit silhouette and the added allure of a floral print, this dress is a versatile and refined choice for any occasion, offering a touch of vintage-inspired sophistication to your wardrobe.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 42,
                        origin: 'Imported',
                        material: '100% Viscose',
                        productTypeName: 'dresses',
                        slug: 'going-out-and-about-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760692819901,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f21fc30b5dc27f73097b1e',
                        name: 'The Vivienne V-Neck Dress',
                        description:
                            'Classic lines meet vintage-inspired flair in The Vivienne V-Neck Dress from our ModCloth namesake label. Featuring a flattering V-neckline, a wide defined waistband, and a perfectly twirlable fit-and-flare silhouette, this dress was made for everything from dinner dates to daytime strolls. Polished, playful, and effortlessly chic—this is one you’ll wear on repeat.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: 'Shell and Contrast:100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'the-vivienne-v-neck-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760698307190,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f220630b5dc27f73097b24',
                        name: 'Goldie Hour V-Neck Midi Dress',
                        description:
                            'Wrap yourself in the warmth of nostalgia with the Goldie Hour Midi Dress. This piece from our ModCloth namesake label exudes a rustic charm with its terra cotta paisley pattern on soft knit fabric. Balloon long sleeves and a smock panel enhance its vintage flair, while pockets add a touch of modern functionality. Its medium stretch fabric and v-neckline adorned with button details make it a cozy yet chic choice for winter get-togethers or a romantic evening at the drive-in.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 48,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'goldie-hour-v-neck-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760698467410,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f221180b5dc27f73097b2a',
                        name: 'Instant Energy Faux-Wrap Dress',
                        description:
                            'Instant Energy Faux-Wrap Dress from our ModCloth namesake label is a bold statement. This printed cotton dress offers the comfort of a woven fabric with the added convenience of pockets and a secure zipper closure. This faux-wrap wonder is a conversation starter at art shows, midnight movie premieres, or any occasion that calls for a dash of the extraordinary.',
                        price: 119,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 42.5,
                        origin: 'Imported',
                        material: 'Shell and Lining:100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'instant-energy-faux-wrap-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760698648235,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f221ca0b5dc27f73097b30',
                        name: 'Such a Love Midi Dress',
                        description:
                            'Wrap yourself in the rich tones of the Such a Love Midi Dress from our ModCloth namesake label. This emerald knit wonder features a flirtatious sweetheart neck, a playful ruffle hem, and a snug smock panel for that perfect fit. With medium stretch for comfort and a keyhole closure for a charming back detail, this dress is a winter favorite for date nights or cozy gatherings. Its versatile style makes transitioning from daydreaming at home to festive soirées absolutely seamless.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 49,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'such-a-love-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760698826300,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f2238b0b5dc27f73097b36',
                        name: 'All About the Doodlebug Fit & Flare Dress',
                        description:
                            'Embrace a playful pattern with the All About the Doodlebug Fit & Flare Dress in cherry grid from our ModCloth namesake label. This red plaid knit dress offers a fetching fit-and-flare silhouette with a boatneck and three-quarter sleeves. The medium stretch and secure zipper make it a stylish staple for harvest festivals or pumpkin patch visits.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 39,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'all-about-the-doodlebug-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760699275107,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f225990b5dc27f73097b3c',
                        name: 'Elegance Anew Fit & Flare Dress',
                        description:
                            "From our ModCloth namesake label, the Elegance Anew Fit & Flare Dress is your ticket to timeless elegance this fall. The brushed fabric creates a soft, medium stretch knit that contours delicately to your figure. With its iconic Jackie O-inspired collar, this piece combines retro charm with modern sophistication. Perfect for autumn weddings or sophisticated pumpkin spice outings, it's a wardrobe staple that embodies the spirit of the season.",
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'elegance-anew-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760699801959,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f227c20b5dc27f73097b42',
                        name: 'Simply Sublime Fit & Flare Pleated Dress',
                        description:
                            "Fall in love with the Simply Sublime Fit & Flare Pleated Dress, a standout piece from our ModCloth namesake label. This dress features a scoop neckline adorned with contrast trim, a fitted bodice, and a gracefully pleated skirt. Functional button closures and an elastic waist ensure a perfect fit. It's an enchanting choice for day dates and twirl-worthy occasions this fall.",
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 34.5,
                        origin: 'Imported',
                        material: 'Shell and Contrast: 100% Polyester Lining: 95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'simply-sublime-fit-flare-pleated-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760700354074,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f228560b5dc27f73097b48',
                        name: 'Top of the Morning Shirt Waist Dress',
                        description:
                            'The Top of the Morning Shirt Waist Dress is an autumnal dream, weaving vintage allure with modern functionality. Made from crepe fabric, it includes practical pockets and a graceful elastic waist. From our ModCloth namesake label, this piece is ideal for commanding attention in the boardroom or sipping cider under the stars.',
                        price: 129,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37.5,
                        origin: 'Imported',
                        material: '100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'top-of-the-morning-shirt-waist-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760700502430,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f228d00b5dc27f73097b4e',
                        name: 'Garden Party Tapestry Midi Dress',
                        description:
                            "Dive into the elegance of yesteryear with the Garden Party Tapestry Midi Dress, a striking piece from our ModCloth namesake label. Infused with the romance of a celestial navy swirl pattern, its paisley design evokes the magic and mystery of starlit evenings. This dress is a comfortable yet stylish choice with its medium-stretch knit fabric, ensuring ease of movement for any event. Thoughtfully designed with pockets and a smock panel for a perfect fit, it's a dress that marries form and function beautifully.",
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 48,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'garden-party-tapestry-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760700624312,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f229350b5dc27f73097b54',
                        name: 'Twilight Serenade Midi Dress',
                        description:
                            'From our ModCloth namesake label comes the Twilight Serenade Midi Dress, a nostalgic ode to vintage charm with a modern twist. Clad in a striking crimson check, this knit piece offers a flattering double scoop neck top and a contrasting skirt, accented with a sash waist for a defined silhouette. Medium stretch ensures comfort and flexibility, while a discreet pocket adds a functional touch. Ideal for festive gatherings or cozy winter dates, this dress guarantees a stunning entrance.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 49,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'twilight-serenade-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760700725735,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f229ed0b5dc27f73097b5a',
                        name: 'Garden Stroll Fit & Flare Dress',
                        description:
                            'Bring a touch of vintage romance to your everyday with the Garden Stroll Dress from our ModCloth namesake label. Made from 100% cotton for breathable comfort, this fit and flare silhouette is as timeless as it is flattering. The puff sleeves and square neckline give a nod to retro charm, while the smocked back with tie detail keeps it easy and comfortable. Pockets add that essential dose of practicality, perfect for a countryside bike ride or a city café run. In our Autumn Bloom print—golden ochre and sky-blue florals on a deep navy base—this dress is ready to take you from sunlit strolls to starry evenings.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 48,
                        origin: 'Imported',
                        material: '100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'garden-stroll-fit-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760700909598,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22a550b5dc27f73097b60',
                        name: 'Garden Party Tapestry Midi Dress',
                        description:
                            'The Garden Party Tapestry Midi Dress from our ModCloth namesake label takes on a fresh, boho-meets-romance vibe in this paisley-infused print. Deep burgundy sets the stage for swirling teals, golden ochres, and delicate florals, giving the dress an effortless vintage allure. The mock neck and long sleeves keep things polished, while the flowing midi silhouette promises comfort and grace at every turn. Whether you’re twirling through fall festivals or sipping cocktails by candlelight, this dress captures that perfect mix of elegance and ease.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 48,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'garden-party-tapestry-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701013475,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22acd0b5dc27f73097b66',
                        name: 'Plaid & Prejudice Dress',
                        description:
                            'Step into classic charm with the Plaid & Prejudice Dress from our ModCloth namesake label. Featuring a timeless black-and-white plaid, playful puff sleeves with ruffle trim, and a belted waist that cinches just right, this dress is equal parts sweet and structured. Crafted from a soft stretch blend, it moves with you while keeping its polished silhouette. Oh, and yes—it has pockets, because practicality is always in style.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 36,
                        origin: 'Imported',
                        material: '92% Polyester, 6% Viscose, 2% Elastane',
                        productTypeName: 'dresses',
                        slug: 'plaid-prejudice-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701133824,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22bb60b5dc27f73097b6c',
                        name: 'Twilight Serenade Midi Dress',
                        description:
                            'From our ModCloth namesake label comes the Twilight Serenade Midi Dress, a nostalgic ode to vintage charm with a modern twist. Clad in a rich purple check, this knit piece offers a flattering double scoop neck top and a contrasting skirt, accented with a sash waist for a defined silhouette. Medium stretch ensures comfort and flexibility, while a discreet pocket adds a functional touch. Ideal for festive gatherings or cozy winter dates, this dress guarantees a stunning entrance.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 49,
                        origin: 'Imported',
                        material: '92% Polyester, 8%, Elastane',
                        productTypeName: 'dresses',
                        slug: 'twilight-serenade-midi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701366006,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22c2f0b5dc27f73097b72',
                        name: 'Penmanship Perfection Dress',
                        description:
                            'Let your style make its mark in the Penmanship Perfection Dress from our ModCloth namesake label. Featuring the whimsical Write On print, this sleeveless A-line cut is equal parts witty and wearable. The soft fabric drapes just right, while the contrast bow collar adds a polished finish to your creative flair. Bonus points: pockets that are ready to hold your pens—or just your phone. Whether you’re sketching, scribbling, or simply standing out, this dress is proof that fashion and clever wordplay go hand in hand.',
                        price: 69,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 35,
                        origin: 'Imported',
                        material: '95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'penmanship-perfection-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701487960,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22cbd0b5dc27f73097b78',
                        name: 'Checkmate Charm Dress',
                        description:
                            'Bring a touch of vintage edge to your everyday with the Checkmate Charm Dress from our ModCloth namesake label. Crafted in a rich plum plaid, this sleeveless A-line dress is cinched with a matching belt and finished with a sweet bow at the neckline. Its flattering fit and subtle stretch make it an instant classic for layering with cardigans, tights, or boots. Pockets included—because practicality never goes out of style.',
                        price: 109,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 37,
                        origin: 'Imported',
                        material: '100% Viscose',
                        productTypeName: 'dresses',
                        slug: 'checkmate-charm-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701629013,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22d8e0b5dc27f73097b7e',
                        name: 'Gingham Swing Dress',
                        description:
                            'Timeless and playful, the Gingham Swing Dress by Orchid Bloom is a vintage-inspired staple with a modern twist. Featuring a charming gingham pattern and a flattering swing silhouette, this dress is perfect for picnics, weekend outings, and sunny-day style.',
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: '97% Polyester, 3% Spandex',
                        productTypeName: 'dresses',
                        slug: 'gingham-swing-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701838859,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22e1d0b5dc27f73097b84',
                        name: 'Yellow Plaid Swing Dress',
                        description:
                            "Brighten your wardrobe with the Yellow Plaid Swing Dress by Orchid Bloom. Featuring a classic swing silhouette and a vibrant plaid in sunny yellow and mustard tones, this dress adds retro flair and feel-good energy to any outfit.\nMade from a breathable cotton-spandex blend, it offers just the right amount of stretch for a flattering, comfortable fit. Finished with a center back zipper and functional side pockets, it's as practical as it is eye-catching.",
                        price: 89,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: '97% Polyester, 3% Spandex',
                        productTypeName: 'dresses',
                        slug: 'yellow-plaid-swing-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760701981564,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f22f1d0b5dc27f73097b8a',
                        name: 'Black & White Minnie Halter Dress',
                        description:
                            'A fun and flirty tribute to vintage glamour, the Orchid Bloom Black & White Minnie Halter Dress is the perfect throwback to classic 50s style! With its large white polka dots dancing across a timeless black background, this swing dress brings effortless charm and a hint of mischief to any wardrobe.',
                        price: 59.25,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: '97% Cotton, 3% Spandex – fabric provides stretch',
                        productTypeName: 'dresses',
                        slug: 'black-white-minnie-halter-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760702237377,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f234ab0b5dc27f73097b8d',
                        name: 'Prairie Gaze Western Shirtdress',
                        description:
                            'Capture the essence of spring with the Prairie Gaze Western Shirtdress from our ModCloth namesake label. Fashioned in breezy chambray, this dress combines classic western motifs with modern charm. It features a pleated detail, functional buttons, and pockets for practicality, wrapped in a lightweight pullover design. Ideal for both outdoor adventures and casual chic gatherings, it’s a versatile addition to your seasonal wardrobe.',
                        price: 89.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash',
                        length: 38.5,
                        origin: 'Imported',
                        material: 'Shell: 55% Viscose, 45% Polyester Lining: 100% Viscose Contrast: 100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'prairie-gaze-western-shirtdress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760703659366,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f2355d0b5dc27f73097b93',
                        name: 'Leaves Greta Dress',
                        description:
                            'The Greta is everything you could want and more!  Shown in our Leaves print, this vintage style cotton dress features a gathered surplice neckline, cummerbund waist with figure flattering gathers, a vintage inspired twirl-worthy skirt with hidden side pockets, and a back zippered closure.',
                        price: 99.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash',
                        length: 40,
                        origin: 'Made in USA',
                        material: '100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'leaves-greta-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760703837066,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f235fa0b5dc27f73097b99',
                        name: 'The Taffy Twist Halter Dress',
                        description:
                            'Sugar, stripe, and everything nice—The Taffy Twist Halter Dress is a swirl of vintage sweetness from our ModCloth namesake label. With its candy-colored diagonal stripes, flattering A-line silhouette, and bow-tied halter neckline that charms from front to back, this sundress is pure summer nostalgia. A coordinating belt cinches the waist just right, while the soft drape of the skirt keeps things twirl-friendly.',
                        price: 59.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold',
                        length: 42,
                        origin: 'Imported',
                        material: '80% Polyester, 20% Cotton',
                        productTypeName: 'dresses',
                        slug: 'the-taffy-twist-halter-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760703994481,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f236700b5dc27f73097ba0',
                        name: 'Black White Checkmate Halter Dress',
                        description:
                            'Make your next move a stylish one with the Orchid Bloom Black & White Checkmate Halter Dress! Featuring a bold checkerboard print and a flattering halter neckline, this retro-inspired stunner is made for twirling, winning hearts, and standing out from the crowd. Crafted from a breathable cotton-spandex blend, it’s a playful nod to vintage cool with a modern twist.',
                        price: 66.75,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, tumble dry low or hang to air-dry',
                        length: 42,
                        origin: 'Imported',
                        material: '97% Cotton, 3% Spandex',
                        productTypeName: 'dresses',
                        slug: 'black-white-checkmate-halter-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704112748,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f2372a0b5dc27f73097ba6',
                        name: "Can't Slow My Roll Shirt Dress",
                        description:
                            'Step into a spectrum of delight with this ModCloth namesake label lively midi shirt dress.  The smart collared top and button-down front fuse timeless style with modern flair, while the tie waist cinches to accentuate your silhouette beautifully. Ideal for brunches under the sun or casual gallery visits, this dress promises comfort and a dash of joy in every seam.',
                        price: 79.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 41,
                        origin: 'Imported',
                        material: 'Shell: 100% Cotton, Lining: 100% Viscose',
                        productTypeName: 'dresses',
                        slug: 'cant-slow-my-roll-shirt-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704298224,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f237c70b5dc27f73097bac',
                        name: 'November Nostalgia Flare Dress',
                        description:
                            "November Nostalgia Flare Dress from our ModCloth namesake label wraps you in the warmth of autumn memories with its black and red checkered pattern. This knit, med-stretch fabric dress combines the joy of days gone by with the comfort of today, featuring a fit and flare silhouette that flatters every body type. The contrast collar and tie bring a playful vibe, while the keyhole closure and pockets add practicality to its charm. Whether you're sipping cider at a fall festival or strolling through the leaves, this dress is your go-to for making new memories.",
                        price: 79,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 34,
                        origin: 'Imported',
                        material: 'Shell: 95% Polyester, 5% Elastane Contrast: 100% Polyester',
                        productTypeName: 'dresses',
                        slug: 'november-nostalgia-flare-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704455825,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f2383c0b5dc27f73097bb2',
                        name: 'The Peggy Sue Shirt Dress',
                        description:
                            'Sweet, smart, and ready for anything—The Peggy Sue Shirt Dress from our ModCloth namesake label channels classic ‘50s charm with a modern twist. Featuring a crisp collar, short sleeves, and a button-front design, this easygoing fit brings vintage polish to your everyday lineup. Whether you belt it, layer it, or let it swing free, it’s the kind of timeless staple you’ll reach for again and again.',
                        price: 69.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold',
                        length: 37,
                        origin: 'Imported',
                        material: 'Shell: 100% Polyester, Lining: 95% Polyester, 5% Elastane',
                        productTypeName: 'dresses',
                        slug: 'the-peggy-sue-shirt-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704572684,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f238c10b5dc27f73097bb8',
                        name: 'Yellow and Red Rose Swing Dress',
                        description:
                            'Fresh as a garden breeze and just as charming—the Orchid Bloom Yellow with Red Rose Swing Dress is a blooming beauty. Featuring a vintage-inspired silhouette, this dress is adorned with a cheerful red rose print on a soft yellow backdrop. With contrast piping, a dainty bow at the neckline, and a flared swing skirt, it’s a picture-perfect piece for sunny strolls and sweet soirees.',
                        price: 66.75,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, tumble dry low or hang to air-dry',
                        length: 41,
                        origin: 'Imported',
                        material: '97% Cotton, 3% Spandex – fabric provides stretch',
                        productTypeName: 'dresses',
                        slug: 'yellow-and-red-rose-swing-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704705613,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f239ba0b5dc27f73097bbe',
                        name: 'The Stargarden Romper',
                        description:
                            "Bloom where you're romped in The Stargarden Romper, a playful floral one-piece from our ModCloth namesake label. With a soft drape of 100% viscose, this style features cap sleeves, a keyhole neckline, and an enchanting mix of star-speckled navy and vivid pink blooms.",
                        price: 64.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold',
                        length: 42.5,
                        origin: 'Imported',
                        material: '97% Cotton, 3% Spandex – fabric provides stretch',
                        productTypeName: 'dresses',
                        slug: 'the-stargarden-romper',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760704954558,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f23a3b0b5dc27f73097bc4',
                        name: 'Glimmering Goddess Maxi Dress',
                        description:
                            'Embrace the warmth of the sun in this mustard yellow tiered maxi dress, another gem from our ModCloth namesake label. Sleeveless and serene, this dress cascades effortlessly down in beautiful tiers, creating a dance of light and fabric with every move you make. Ideal for balmy day ventures or serene evening soirees, its vibrant color brings a cheerful aura wherever it goes. Its airy, breathable fabric ensures endless comfort, making it a perfect companion for leisurely walks or sophisticated gatherings under the open sky.',
                        price: 31.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, line dry',
                        length: 40,
                        origin: 'Imported',
                        material: '100% Cotton',
                        productTypeName: 'dresses',
                        slug: 'glimmering-goddess-maxi-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760705083253,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f23ab80b5dc27f73097bca',
                        name: 'Vintage Vision Tie-Neck Dress',
                        description:
                            "Step into spring with the Vintage Vision Tie-Neck Dress in Rose Glimmer, exclusively from our ModCloth namesake label. This knit dress, boasting a high-stretch fabric and a graceful tie-neck detail, offers both comfort and elegance. The zipper closure ensures a perfect fit, making it ideal for Valentine's gatherings or a leisurely stroll through blooming gardens. Its soft, rose hue captures the essence of vintage whimsy, promising to be a favorite in your wardrobe.",
                        price: 64.99,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash',
                        length: 35.5,
                        origin: 'Imported',
                        material: 'Shell: 85% Polyester, 15% Elastane',
                        productTypeName: 'dresses',
                        slug: 'vintage-vision-tie-neck-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760705208010,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f23b300b5dc27f73097bd0',
                        name: 'Sunnyside Romper',
                        description:
                            'Add a playful pop of retro fun to your wardrobe with the Orchid Bloom Sunnyside Romper. Featuring a cheerful print of daisies, sunglasses, and bicycles on a soft cream background, this romper brings vintage charm to sunny days. The fitted bodice and high-waisted shorts create a flattering silhouette, while the cotton-spandex blend ensures comfort and a hint of stretch. Finished with convenient side pockets and a side zipper for effortless dressing, this romper is your new go-to for picnics, beach days, or just soaking up the sun.',
                        price: 44.25,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash',
                        length: 36,
                        origin: 'Imported',
                        material: '97% Cotton / 3% Spandex',
                        productTypeName: 'dresses',
                        slug: 'sunnyside-romper',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760705328232,
                        updatedAt: null,
                        _destroy: false,
                    },
                    {
                        _id: '68f23b910b5dc27f73097bd5',
                        name: 'Green & White Polka Dot Dress',
                        description:
                            'Dot your day with charm in the Orchid Bloom Green & White Polka Dot Dress! With its classic fit-and-flare shape and cheerful print, this cotton-blend cutie is made for garden parties, twirls in the park, and spontaneous compliments. The soft stretch keeps things comfy, while the vintage vibes keep things totally unforgettable.',
                        price: 66.75,
                        productTypeId: '68f11e49d8150dda53806919',
                        stockQuantity: 100,
                        careIntroduction: 'Machine wash cold, tumble dry low or hang to air-dry',
                        length: 36,
                        origin: 'Imported',
                        material: '97% Cotton, 3% Spandex',
                        productTypeName: 'dresses',
                        slug: 'green-white-polka-dot-dress',
                        title: '',
                        imageOrderIds: [],
                        createdAt: 1760705425706,
                        updatedAt: null,
                        _destroy: false,
                    },
                ],
            },
            { id: '2', name: 'tops' },
            { id: '3', name: 'bottoms' },
            { id: '4', name: 'bags' },
            { id: '5', name: 'shoes' },
            { id: '6', name: 'jewelry' },
        ],
        orders: [
            {
                id: 'o1',
                userId: 'u1', // liên kết với user
                createdAt: '2025-10-16T10:00:00Z',
                status: [], // trạng thái đơn hàng (pending, shipped, completed...)
                totalPrice: 100, // tổng tiền đơn hàng (có thể tính ra hoặc lưu sẵn)
                orderItems: [
                    {
                        id: 'oi1',
                        productId: 'p1', // liên kết với sản phẩm
                        quantity: 2,
                        price: 15, // giá tại thời điểm mua (để tránh thay đổi giá sản phẩm sau đó ảnh hưởng đơn hàng)
                        totalPrice: 30,
                    },
                    {
                        id: 'oi2',
                        productId: 'p2',
                        quantity: 1,
                        price: 40,
                        totalPrice: 40,
                    },
                ],
            },
        ],
    },
};
